### ISSUE TITLE
Classify my own audio file

### ISSUE THREAD

**Issue by gingerbeardman** [ashaydave/music-genre-classification-basic#1]
Your code was very easy to run. So thanks for keeping it simple!

Is it possible for me to classify my own audio on the same setup?

Thanks!

**Comment by ashaydave** [comment]
Thank you! You should be able to classify your own audio files although it's better to structure them similar to how the GTZAN dataset is structured (putting all the tracks into a genre sub-folder). Also, the tracks in the dataset are only 30 seconds long, so if your files are longer edit this line here in preprocess.py:

``` 
TRACK_DURATION = 30 # measured in seconds
```

And in the samples_per_segment var, just multiply 22050 by the track duration (I hard coded the value in this one, not ideal, but since I knew the tracks are 30 seconds long anyway...)

```
 samples_per_segment = 22050 * 30 # multiply it with the track duration here instead of 30.
 ```

**Comment by gingerbeardman** [comment]
Thanks, I'll try it. 

I'll prepare some 30 second 22050Hz snippets of my files.

**Comment by ashaydave** [comment]
You can use 44100 Hz audio as well, the GTZAN dataset has audio sampled at 22050 Hz. You'll just have to change the sample rate to 44100, and samples per segment will instead be 44100 * 30.

**Comment by gingerbeardman** [comment]
So using your code I can (correct me if I am wrong):

1. preprocess to produce the model data from GTZAN
2. process_cnn to show the chart

What I'd like to do is for my own audio, print what genre it is, based on the already generated data file

**Comment by ashaydave** [comment]
Yes, that is correct. Here is the link to the dataset that I downloaded from: https://www.kaggle.com/datasets/andradaolteanu/gtzan-dataset-music-genre-classification

**Comment by ashaydave** [comment]
Although just a note - the genres are really broad and it is possible the model won't be able to classify something like "alternative rock" or "techno" or something. Alternative rock would be classified as rock or pop, and techno would probably be classified as disco.

**Comment by gingerbeardman** [comment]
That's OK, I am happy with the broad genres.

I am putting some music into a game and want the user to be able to add their own music. So I am experimenting with a way for the user to generate metadata alongside their audio file.

I'll see if I can create some new python to classify my audio.

**Comment by ashaydave** [comment]
That's really interesting! All the best with your game, and if you face any issues lemme know. I've got some experience working on game audio :)

**Comment by gingerbeardman** [comment]
With the help of ChatGPT, because i'm not fluent in python, I created some new files:
- train (to produce a stored model from the data.json)
- classify (to classify my audio)

It's working well, but as you suspected the genre classifications are not really accurate.

I am using 20 segments, which seems to generate a model of slightly higher accuracy.
Also I am trying different classifiers which show different results.
And I am using python to get the most common genre across all segments as the genre for that audio.

i will continue to experiment some more
